/*Criando procedimento para listar os dados da tabela tb_Produtos*/
IF EXISTS (SELECT TOP 1 1 FROM SYS.OBJECTS WHERE TYPE = 'P' AND NAME = 'SP_LISTAR_PRODUTO')
	DROP PROCEDURE SP_LISTAR_PRODUTO
GO

CREATE PROCEDURE SP_LISTAR_PRODUTO
AS
BEGIN
	SELECT *
	FROM tb_Produtos
END